# Site settings
contact: george.lele.sun-x@gmail.com
company_name: Sun Websites
company_website: https://www.sunwebsites.org
personal_website: http://www.mrsunny.tech
template_readme: https://github.com/mrsunny0/template-gh-pages/blob/gh-pages/README.md
template_generator: https://github.com/mrsunny0/generator-gls-website

# Front page settings
author: George L. Sun
title: Project Portfolio
header: Project Portfolio
description: Projects, collaborations, and interests
gh_page: this.example.com
background: 
  video: assets/video/assemble.mp4
  image: assets/img/1000.png 
  color: #1a222c  

# Google-analytics
google-analytics:
  id: "UA-161447266-8"

exclude: ['package.json', 'src' , 'node_modules']
